[versions]
jspecify = "1.0.0"
junit = "6.0.1"

[libraries]
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit" }

[bundles]
junit = [ "junit-jupiter", "junit-launcher" ]

[plugins]
java-library = { id = "java-library" }
maven-publish = { id = "maven-publish" }
